import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// Generates a rich branded PDF for a toolkit tool output.
class PdfDocumentService {
  static const _teal = PdfColor.fromInt(0xFF19CBD6);
  static const _textDark = PdfColor.fromInt(0xFF1E293B);
  static const _textMuted = PdfColor.fromInt(0xFF64748B);
  static const _border = PdfColor.fromInt(0xFFE2E8F0);

  Future<Uint8List> generateToolOutputPdf({
    required String decisionTitle,
    required String toolName,
    required String toolOutput,
    required Map<String, dynamic> toolData,
    required String workspaceName,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateLabel = DateFormat('d MMMM yyyy').format(now);

    // ── Cover page ────────────────────────────────────────────────────────────
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.zero,
        build: (pw.Context context) {
          return pw.Stack(
            children: [
              // Teal top bar
              pw.Positioned(
                top: 0,
                left: 0,
                right: 0,
                child: pw.Container(
                  height: 8,
                  color: _teal,
                ),
              ),
              // Page content
              pw.Padding(
                padding: const pw.EdgeInsets.fromLTRB(48, 48, 48, 48),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.SizedBox(height: 24),
                    // Brand mark
                    pw.Container(
                      width: 56,
                      height: 56,
                      decoration: pw.BoxDecoration(
                        color: _teal,
                        borderRadius: pw.BorderRadius.circular(12),
                      ),
                      child: pw.Center(
                        child: pw.Text(
                          'R',
                          style: pw.TextStyle(
                            color: PdfColors.white,
                            fontSize: 32,
                            fontWeight: pw.FontWeight.bold,
                          ),
                        ),
                      ),
                    ),
                    pw.SizedBox(height: 8),
                    pw.Text(
                      'REFLECT OS',
                      style: pw.TextStyle(
                        color: _teal,
                        fontSize: 11,
                        letterSpacing: 2,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.SizedBox(height: 80),
                    // Decision title
                    pw.Text(
                      decisionTitle,
                      style: pw.TextStyle(
                        color: _textDark,
                        fontSize: 28,
                        fontWeight: pw.FontWeight.bold,
                        lineSpacing: 4,
                      ),
                    ),
                    pw.SizedBox(height: 16),
                    // Tool name
                    pw.Text(
                      toolName,
                      style: pw.TextStyle(
                        color: _teal,
                        fontSize: 16,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.SizedBox(height: 8),
                    pw.Text(
                      'Tool Analysis Report',
                      style: pw.TextStyle(
                        color: _textMuted,
                        fontSize: 13,
                      ),
                    ),
                    pw.Spacer(),
                    pw.Divider(color: _border, thickness: 0.5),
                    pw.SizedBox(height: 12),
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Column(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.Text('Generated by Reflect OS',
                                style: pw.TextStyle(
                                    color: _textMuted, fontSize: 10)),
                            pw.Text(dateLabel,
                                style: pw.TextStyle(
                                    color: _textDark,
                                    fontSize: 11,
                                    fontWeight: pw.FontWeight.bold)),
                          ],
                        ),
                        pw.Text(workspaceName,
                            style: pw.TextStyle(
                                color: _textMuted, fontSize: 10)),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          );
        },
      ),
    );

    // ── Content pages ─────────────────────────────────────────────────────────
    final sections = _parseSections(toolOutput, toolData);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(48, 40, 48, 48),
        header: (pw.Context context) => _pageHeader(
          context,
          decisionTitle,
          dateLabel,
        ),
        footer: (pw.Context context) => _pageFooter(context, dateLabel),
        build: (pw.Context context) => [
          // Scores/ratings bar chart if present
          if (toolData.isNotEmpty) ..._buildScoreBars(toolData),

          // Parsed sections
          for (final section in sections) ...[
            pw.SizedBox(height: 16),
            _buildSection(section),
          ],

          // Fallback: raw text if no structured sections
          if (sections.isEmpty && toolOutput.isNotEmpty) ...[
            pw.SizedBox(height: 16),
            _sectionHeading('Analysis Output'),
            pw.SizedBox(height: 8),
            _bodyText(toolOutput),
          ],
        ],
      ),
    );

    return pdf.save();
  }

  // ── Page header ───────────────────────────────────────────────────────────

  pw.Widget _pageHeader(
    pw.Context context,
    String decisionTitle,
    String dateLabel,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        pw.Container(height: 2, color: _teal),
        pw.SizedBox(height: 6),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('REFLECT OS',
                style: pw.TextStyle(
                    color: _teal, fontSize: 9, letterSpacing: 1.5)),
            pw.Text(
              decisionTitle.length > 60
                  ? '${decisionTitle.substring(0, 57)}…'
                  : decisionTitle,
              style: pw.TextStyle(color: _textMuted, fontSize: 9),
            ),
          ],
        ),
        pw.SizedBox(height: 12),
      ],
    );
  }

  // ── Page footer ───────────────────────────────────────────────────────────

  pw.Widget _pageFooter(pw.Context context, String dateLabel) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        pw.Divider(color: _border, thickness: 0.5),
        pw.SizedBox(height: 4),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Generated $dateLabel',
                style: pw.TextStyle(color: _textMuted, fontSize: 8)),
            pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
                style: pw.TextStyle(color: _textMuted, fontSize: 8)),
          ],
        ),
      ],
    );
  }

  // ── Score bars ────────────────────────────────────────────────────────────

  List<pw.Widget> _buildScoreBars(Map<String, dynamic> data) {
    final numeric = data.entries
        .where((e) => e.value is num && (e.value as num) > 0)
        .toList();
    if (numeric.isEmpty) return [];

    final maxVal =
        numeric.map((e) => (e.value as num).toDouble()).reduce((a, b) => a > b ? a : b);
    if (maxVal == 0) return [];

    // Bar width on A4 page (498pt content width minus 120 label minus 48 value)
    const barAreaWidth = 498.0 - 120 - 48;
    return [
      pw.SizedBox(height: 16),
      _sectionHeading('Key Metrics'),
      pw.SizedBox(height: 8),
      for (final entry in numeric.take(8)) ...[
        pw.Row(
          children: [
            pw.SizedBox(
              width: 120,
              child: pw.Text(
                _humanLabel(entry.key),
                style: pw.TextStyle(color: _textMuted, fontSize: 9),
              ),
            ),
            pw.Expanded(
              child: pw.Row(
                children: [
                  // Filled portion
                  pw.Container(
                    width: barAreaWidth *
                        ((entry.value as num).toDouble() / maxVal)
                            .clamp(0.0, 1.0),
                    height: 10,
                    decoration: pw.BoxDecoration(
                      color: _teal,
                      borderRadius: pw.BorderRadius.circular(4),
                    ),
                  ),
                  // Unfilled portion
                  pw.Expanded(
                    child: pw.Container(
                      height: 10,
                      decoration: pw.BoxDecoration(
                        color: _border,
                        borderRadius: pw.BorderRadius.circular(4),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            pw.SizedBox(width: 8),
            pw.Text(
              _formatNum(entry.value),
              style: pw.TextStyle(
                color: _textDark,
                fontSize: 9,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 6),
      ],
    ];
  }

  // ── Section parser ────────────────────────────────────────────────────────

  List<_Section> _parseSections(String text, Map<String, dynamic> data) {
    final sections = <_Section>[];

    // Try to split by common heading patterns (lines ending with ':' or
    // markdown-style lines starting with '#')
    final lines = text.split('\n');
    String? currentHeading;
    final currentBullets = <String>[];
    final currentBody = StringBuffer();

    void flush() {
      if (currentHeading != null || currentBody.isNotEmpty) {
        sections.add(_Section(
          heading: currentHeading ?? '',
          body: currentBody.toString().trim(),
          bullets: List<String>.from(currentBullets),
        ));
        currentHeading = null;
        currentBullets.clear();
        currentBody.clear();
      }
    }

    for (final raw in lines) {
      final line = raw.trim();
      if (line.isEmpty) continue;

      // Detect heading patterns
      if (line.startsWith('## ') || line.startsWith('# ')) {
        flush();
        currentHeading = line.replaceAll(RegExp(r'^#+\s*'), '');
      } else if (line.endsWith(':') && line.length < 60 && !line.startsWith('-')) {
        flush();
        currentHeading = line.substring(0, line.length - 1);
      } else if (line.startsWith('- ') || line.startsWith('• ')) {
        currentBullets.add(line.substring(2).trim());
      } else if (line.startsWith('* ')) {
        currentBullets.add(line.substring(2).trim());
      } else {
        if (currentBody.isNotEmpty) currentBody.write(' ');
        currentBody.write(line);
      }
    }
    flush();

    return sections;
  }

  pw.Widget _buildSection(_Section section) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        if (section.heading.isNotEmpty) ...[
          _sectionHeading(section.heading),
          pw.SizedBox(height: 6),
        ],
        if (section.body.isNotEmpty) ...[
          _bodyText(section.body),
          pw.SizedBox(height: 8),
        ],
        for (final bullet in section.bullets) ...[
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                width: 6,
                height: 6,
                margin: const pw.EdgeInsets.only(top: 3, right: 8),
                decoration: const pw.BoxDecoration(
                  color: _teal,
                  shape: pw.BoxShape.circle,
                ),
              ),
              pw.Expanded(
                child: pw.Text(
                  bullet,
                  style: pw.TextStyle(color: _textDark, fontSize: 10),
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 4),
        ],
        pw.Divider(color: _border, thickness: 0.5),
      ],
    );
  }

  // ── Widget helpers ────────────────────────────────────────────────────────

  pw.Widget _sectionHeading(String text) {
    return pw.Text(
      text.toUpperCase(),
      style: pw.TextStyle(
        color: _teal,
        fontSize: 11,
        fontWeight: pw.FontWeight.bold,
        letterSpacing: 0.8,
      ),
    );
  }

  pw.Widget _bodyText(String text) {
    return pw.Text(
      text,
      style: pw.TextStyle(
        color: _textDark,
        fontSize: 10,
        lineSpacing: 2,
      ),
      textAlign: pw.TextAlign.justify,
    );
  }

  // ── Formatting helpers ────────────────────────────────────────────────────

  String _humanLabel(String key) {
    return key
        .replaceAll('_', ' ')
        .split(' ')
        .map((w) => w.isEmpty ? '' : '${w[0].toUpperCase()}${w.substring(1)}')
        .join(' ');
  }

  String _formatNum(dynamic v) {
    if (v is double) {
      if (v >= 1000000) return '${(v / 1000000).toStringAsFixed(1)}M';
      if (v >= 1000) return '${(v / 1000).toStringAsFixed(0)}k';
      return v.toStringAsFixed(v == v.truncateToDouble() ? 0 : 2);
    }
    return v.toString();
  }
}

class _Section {
  const _Section({
    required this.heading,
    required this.body,
    required this.bullets,
  });

  final String heading;
  final String body;
  final List<String> bullets;
}
